using System.Globalization;
using System.IO;
using System.Net;
using System.Text;
using System.Text.Json;
using MedWNetworkSim.App.Models;

namespace MedWNetworkSim.App.Services;

/// <summary>
/// Builds network and timeline reports without any actor-specific sections.
/// </summary>
public sealed class ReportExportService
{
    private static readonly StringComparer Comparer = StringComparer.OrdinalIgnoreCase;
    private const string CsvBrandHeader = "# Generated by Turkey Oak Network Simulator";

    public void SaveCurrentReport(
        NetworkModel network,
        IEnumerable<TrafficSimulationOutcome> outcomes,
        IEnumerable<ConsumerCostSummary> consumerCosts,
        string path,
        ReportExportFormat format)
    {
        ArgumentNullException.ThrowIfNull(network);
        ArgumentNullException.ThrowIfNull(outcomes);
        ArgumentNullException.ThrowIfNull(consumerCosts);
        ArgumentException.ThrowIfNullOrWhiteSpace(path);

        var materializedOutcomes = outcomes.ToList();
        var materializedConsumerCosts = consumerCosts.ToList();
        var contents = format switch
        {
            ReportExportFormat.Csv => BuildCurrentCsvReport(network, materializedOutcomes, materializedConsumerCosts),
            ReportExportFormat.Json => BuildCurrentJsonReport(network, materializedOutcomes, materializedConsumerCosts),
            _ => BuildCurrentHtmlReport(network, materializedOutcomes, materializedConsumerCosts)
        };

        File.WriteAllText(path, contents, Encoding.UTF8);
    }

    public void SaveTimelineReport(
        NetworkModel network,
        IReadOnlyList<TemporalNetworkSimulationEngine.TemporalSimulationStepResult> periodResults,
        string path,
        ReportExportFormat format)
    {
        ArgumentNullException.ThrowIfNull(network);
        ArgumentNullException.ThrowIfNull(periodResults);
        ArgumentException.ThrowIfNullOrWhiteSpace(path);

        if (periodResults.Count <= 0)
        {
            throw new InvalidOperationException("Timeline report periods must be greater than zero.");
        }

        var contents = format switch
        {
            ReportExportFormat.Csv => BuildTimelineCsvReport(network, periodResults),
            ReportExportFormat.Json => BuildTimelineJsonReport(network, periodResults),
            _ => BuildTimelineHtmlReport(network, periodResults)
        };

        File.WriteAllText(path, contents, Encoding.UTF8);
    }

    public static string FormatRoutingPreference(RoutingPreference routingPreference) => routingPreference switch
    {
        RoutingPreference.Speed => "Speed",
        RoutingPreference.Cost => "Cost",
        _ => "Total cost"
    };

    public static string FormatNumber(double? value)
    {
        if (!value.HasValue || double.IsPositiveInfinity(value.Value))
        {
            return "Unlimited";
        }

        return value.Value.ToString("0.##", CultureInfo.InvariantCulture);
    }

    public static string FormatCauseBreakdown(
        IReadOnlyDictionary<TemporalNetworkSimulationEngine.PressureCauseKind, double> causeWeights)
    {
        if (causeWeights.Count == 0)
        {
            return "None";
        }

        return string.Join(
            "; ",
            causeWeights
                .Where(pair => pair.Value > 0)
                .OrderByDescending(pair => pair.Value)
                .Select(pair => $"{FormatPressureCause(pair.Key.ToString())} {FormatNumber(pair.Value)}"));
    }

    public static string FormatUtilisation(double flow, double? capacity)
    {
        if (!capacity.HasValue || capacity.Value <= 0)
        {
            return capacity.HasValue && capacity.Value == 0d ? "No capacity" : "Unlimited";
        }

        return $"{(flow / capacity.Value):0%}";
    }

    public static string FormatPressureCause(string? cause)
    {
        if (string.IsNullOrWhiteSpace(cause))
        {
            return string.Empty;
        }

        var normalized = cause.Trim();
        return normalized switch
        {
            "DemandBacklog" => "unmet demand",
            "InputShortage" => "input shortage",
            "StoreCapacitySaturation" => "store capacity saturation",
            "EdgeCapacitySaturation" => "route capacity saturation",
            "TranshipmentCapacitySaturation" => "transhipment saturation",
            "RouteUnavailable" => "route unavailable",
            "PerishedInNodeInventory" => "goods perished in storage",
            "PerishedInTransit" => "goods perished in transit",
            "TimelineShock" => "timeline shock",
            _ => string.Concat(
                normalized.Select((ch, index) =>
                    index > 0 && char.IsUpper(ch) && !char.IsUpper(normalized[index - 1])
                        ? $" {char.ToLowerInvariant(ch)}"
                        : char.ToLowerInvariant(ch).ToString()))
        };
    }

    public static string FormatEdgeTrafficPermissions(NetworkModel network, EdgeModel edge)
    {
        var effectivePermissions = edge.TrafficPermissions
            .Where(rule => rule.IsActive)
            .OrderBy(rule => rule.TrafficType, Comparer)
            .ToList();
        if (effectivePermissions.Count == 0)
        {
            return "Default";
        }

        return string.Join(
            "; ",
            effectivePermissions.Select(rule =>
            {
                var limit = rule.LimitValue.HasValue ? $" ({rule.LimitKind}: {FormatNumber(rule.LimitValue.Value)})" : string.Empty;
                return $"{rule.TrafficType}: {rule.Mode}{limit}";
            }));
    }

    private string BuildCurrentHtmlReport(
        NetworkModel network,
        IReadOnlyList<TrafficSimulationOutcome> outcomes,
        IReadOnlyList<ConsumerCostSummary> consumerCosts)
    {
        var allocations = outcomes.SelectMany(outcome => outcome.Allocations).ToList();
        var builder = CreateHtmlReportHeader("Current Network Report", network);

        AppendHtmlTable(
            builder,
            ["Measure", "Value"],
            [
                ["Nodes", network.Nodes.Count.ToString(CultureInfo.InvariantCulture)],
                ["Edges", network.Edges.Count.ToString(CultureInfo.InvariantCulture)],
                ["Traffic Types", network.TrafficTypes.Count.ToString(CultureInfo.InvariantCulture)],
                ["Sell local meeting-demand limit", FormatOnOff(network.LimitMeetingNodeDemandBySellLocalPermission)],
                ["Total Routed Movements", allocations.Count.ToString(CultureInfo.InvariantCulture)],
                ["Total Delivered", FormatNumber(outcomes.Sum(outcome => outcome.TotalDelivered))]
            ]);

        AppendHtmlTable(
            builder,
            ["Traffic Type", "Preference", "Production", "Consumption", "Delivered", "Unused Supply", "Unmet Demand"],
            outcomes.Select(outcome => new[]
            {
                outcome.TrafficType,
                FormatRoutingPreference(outcome.RoutingPreference),
                FormatNumber(outcome.TotalProduction),
                FormatNumber(outcome.TotalConsumption),
                FormatNumber(outcome.TotalDelivered),
                FormatNumber(outcome.UnusedSupply),
                FormatNumber(outcome.UnmetDemand)
            }));

        AppendHtmlTable(
            builder,
            ["Traffic Type", "Consumer", "Local Qty", "Imported Qty", "Blended Unit Cost", "Total Movement Cost"],
            consumerCosts.Select(summary => new[]
            {
                summary.TrafficType,
                $"{summary.ConsumerName} ({summary.ConsumerNodeId})",
                FormatNumber(summary.LocalQuantity),
                FormatNumber(summary.ImportedQuantity),
                FormatNumber(summary.BlendedUnitCost),
                FormatNumber(summary.TotalMovementCost)
            }));

        AppendHtmlTable(
            builder,
            ["Traffic Type", "Producer", "Consumer", "Qty", "Path", "Time", "Delivered Cost"],
            allocations.Select(allocation => new[]
            {
                allocation.TrafficType,
                allocation.ProducerName,
                allocation.ConsumerName,
                FormatNumber(allocation.Quantity),
                string.Join(" -> ", allocation.PathNodeNames),
                FormatNumber(allocation.TotalTime),
                FormatNumber(allocation.DeliveredCostPerUnit)
            }));

        return FinishHtmlReport(builder);
    }

    private string BuildTimelineHtmlReport(
        NetworkModel network,
        IReadOnlyList<TemporalNetworkSimulationEngine.TemporalSimulationStepResult> periodResults)
    {
        var periods = periodResults.Count;
        var builder = CreateHtmlReportHeader($"Timeline Report ({periods} periods)", network);
        var allAllocations = periodResults.SelectMany(result => result.Allocations).ToList();
        var finalPeriodResult = periodResults[^1];

        AppendHtmlTable(
            builder,
            ["Measure", "Value"],
            [
                ["Periods Simulated", periods.ToString(CultureInfo.InvariantCulture)],
                ["Loop Length", network.TimelineLoopLength?.ToString(CultureInfo.InvariantCulture) ?? "None"],
                ["Sell local meeting-demand limit", FormatOnOff(network.LimitMeetingNodeDemandBySellLocalPermission)],
                ["Allocations Planned", allAllocations.Count.ToString(CultureInfo.InvariantCulture)],
                ["Total Quantity Planned", FormatNumber(allAllocations.Sum(allocation => allocation.Quantity))],
                ["Final In-Flight Movements", finalPeriodResult.InFlightMovementCount.ToString(CultureInfo.InvariantCulture)]
            ]);

        AppendHtmlTable(
            builder,
            ["Traffic Type", "Planned Quantity", "Movements", "Avg Planned Delivered Cost / Unit"],
            allAllocations
                .GroupBy(allocation => allocation.TrafficType, Comparer)
                .OrderBy(group => group.Key, Comparer)
                .Select(group =>
                {
                    // Bolt: Accumulate statistics in a single loop to avoid multiple O(N) LINQ enumerations and delegate allocations
                    var totalQuantity = 0d;
                    var totalMovementCost = 0d;
                    var count = 0;
                    foreach (var item in group)
                    {
                        totalQuantity += item.Quantity;
                        totalMovementCost += item.TotalMovementCost;
                        count++;
                    }

                    return new[]
                    {
                        group.Key,
                        FormatNumber(totalQuantity),
                        count.ToString(CultureInfo.InvariantCulture),
                        FormatNumber(totalQuantity > 0 ? totalMovementCost / totalQuantity : 0d)
                    };
                }));

        foreach (var stepResult in periodResults)
        {
            builder.AppendLine($"<h2>{HtmlEncode(FormatTimelinePeriodLabel(network, stepResult))}</h2>");
            AppendHtmlTable(
                builder,
                ["Measure", "Value"],
                [
                    ["New Quantity Started This Period", FormatNumber(stepResult.Allocations.Sum(allocation => allocation.Quantity))],
                    ["Movements Planned", stepResult.Allocations.Count.ToString(CultureInfo.InvariantCulture)],
                    ["In-Flight After Period", stepResult.InFlightMovementCount.ToString(CultureInfo.InvariantCulture)],
                    ["Nodes With Pressure", stepResult.NodePressureById.Count(snapshot => snapshot.Value.Score > 0).ToString(CultureInfo.InvariantCulture)],
                    ["Edges With Pressure", stepResult.EdgePressureById.Count(snapshot => snapshot.Value.Score > 0).ToString(CultureInfo.InvariantCulture)]
                ]);
        }

        return FinishHtmlReport(builder);
    }

    private string BuildCurrentCsvReport(
        NetworkModel network,
        IReadOnlyList<TrafficSimulationOutcome> outcomes,
        IReadOnlyList<ConsumerCostSummary> consumerCosts)
    {
        var allocations = outcomes.SelectMany(outcome => outcome.Allocations).ToList();
        var builder = new StringBuilder();
        AppendCsvBranding(builder);
        AppendCsvTitleBlock(builder, "Current Network Report", network);
        AppendCsvTable(builder, "Traffic Outcomes", ["Traffic Type", "Preference", "Production", "Consumption", "Delivered", "Unused Supply", "Unmet Demand"],
            outcomes.Select(outcome => new[]
            {
                outcome.TrafficType,
                FormatRoutingPreference(outcome.RoutingPreference),
                FormatNumber(outcome.TotalProduction),
                FormatNumber(outcome.TotalConsumption),
                FormatNumber(outcome.TotalDelivered),
                FormatNumber(outcome.UnusedSupply),
                FormatNumber(outcome.UnmetDemand)
            }));
        AppendCsvTable(builder, "Consumer Costs", ["Traffic Type", "Consumer", "Local Qty", "Imported Qty", "Blended Unit Cost", "Total Movement Cost"],
            consumerCosts.Select(summary => new[]
            {
                summary.TrafficType,
                $"{summary.ConsumerName} ({summary.ConsumerNodeId})",
                FormatNumber(summary.LocalQuantity),
                FormatNumber(summary.ImportedQuantity),
                FormatNumber(summary.BlendedUnitCost),
                FormatNumber(summary.TotalMovementCost)
            }));
        AppendCsvTable(builder, "Routed Movements", ["Traffic Type", "Producer", "Consumer", "Qty", "Path", "Time", "Delivered Cost"],
            allocations.Select(allocation => new[]
            {
                allocation.TrafficType,
                allocation.ProducerName,
                allocation.ConsumerName,
                FormatNumber(allocation.Quantity),
                string.Join(" -> ", allocation.PathNodeNames),
                FormatNumber(allocation.TotalTime),
                FormatNumber(allocation.DeliveredCostPerUnit)
            }));
        return builder.ToString();
    }

    private string BuildTimelineCsvReport(
        NetworkModel network,
        IReadOnlyList<TemporalNetworkSimulationEngine.TemporalSimulationStepResult> periodResults)
    {
        var builder = new StringBuilder();
        AppendCsvBranding(builder);
        AppendCsvTitleBlock(builder, "Timeline Report", network);
        AppendCsvTable(builder, "Timeline Summary", ["Period", "Planned Qty", "Movements", "In Flight", "Node Pressure", "Edge Pressure"],
            periodResults.Select(step => new[]
            {
                step.Period.ToString(CultureInfo.InvariantCulture),
                FormatNumber(step.Allocations.Sum(allocation => allocation.Quantity)),
                step.Allocations.Count.ToString(CultureInfo.InvariantCulture),
                step.InFlightMovementCount.ToString(CultureInfo.InvariantCulture),
                step.NodePressureById.Count(snapshot => snapshot.Value.Score > 0).ToString(CultureInfo.InvariantCulture),
                step.EdgePressureById.Count(snapshot => snapshot.Value.Score > 0).ToString(CultureInfo.InvariantCulture)
            }));
        return builder.ToString();
    }

    private static string BuildCurrentJsonReport(
        NetworkModel network,
        IReadOnlyList<TrafficSimulationOutcome> outcomes,
        IReadOnlyList<ConsumerCostSummary> consumerCosts)
    {
        return JsonSerializer.Serialize(new
        {
            network = new
            {
                network.Name,
                network.Description,
                nodes = network.Nodes.Count,
                edges = network.Edges.Count,
                limitMeetingNodeDemandBySellLocalPermission = network.LimitMeetingNodeDemandBySellLocalPermission
            },
            trafficOutcomes = outcomes.Select(outcome => new
            {
                outcome.TrafficType,
                routingPreference = FormatRoutingPreference(outcome.RoutingPreference),
                outcome.TotalProduction,
                outcome.TotalConsumption,
                outcome.TotalDelivered,
                outcome.UnusedSupply,
                outcome.UnmetDemand
            }),
            consumerCosts,
            allocations = outcomes.SelectMany(outcome => outcome.Allocations).Select(allocation => new
            {
                allocation.TrafficType,
                allocation.ProducerNodeId,
                allocation.ConsumerNodeId,
                allocation.Quantity,
                allocation.TotalTime,
                allocation.DeliveredCostPerUnit,
                allocation.PathNodeIds,
                allocation.PathEdgeIds
            })
        }, new JsonSerializerOptions { WriteIndented = true });
    }

    private static string BuildTimelineJsonReport(
        NetworkModel network,
        IReadOnlyList<TemporalNetworkSimulationEngine.TemporalSimulationStepResult> periodResults)
    {
        return JsonSerializer.Serialize(new
        {
            network = new
            {
                network.Name,
                network.Description,
                nodes = network.Nodes.Count,
                edges = network.Edges.Count,
                limitMeetingNodeDemandBySellLocalPermission = network.LimitMeetingNodeDemandBySellLocalPermission
            },
            periods = periodResults.Select(step => new
            {
                step.Period,
                plannedQuantity = step.Allocations.Sum(allocation => allocation.Quantity),
                movements = step.Allocations.Count,
                step.InFlightMovementCount,
                nodePressureCount = step.NodePressureById.Count(snapshot => snapshot.Value.Score > 0),
                edgePressureCount = step.EdgePressureById.Count(snapshot => snapshot.Value.Score > 0)
            })
        }, new JsonSerializerOptions { WriteIndented = true });
    }

    private static StringBuilder CreateHtmlReportHeader(string title, NetworkModel network)
    {
        var builder = new StringBuilder();
        builder.AppendLine("<!DOCTYPE html>");
        builder.AppendLine("<html lang=\"en\">");
        builder.AppendLine("<head><meta charset=\"utf-8\" />");
        builder.AppendLine($"<title>{HtmlEncode(title)}</title>");
        builder.AppendLine("</head><body>");
        builder.AppendLine($"<h1>{HtmlEncode(title)}</h1>");
        builder.AppendLine($"<p><strong>Generated:</strong> {HtmlEncode(DateTimeOffset.Now.ToString("yyyy-MM-dd HH:mm:ss zzz"))}</p>");
        builder.AppendLine($"<p><strong>Network:</strong> {HtmlEncode(network.Name)}</p>");
        if (!string.IsNullOrWhiteSpace(network.Description))
        {
            builder.AppendLine($"<p>{HtmlEncode(network.Description.Trim())}</p>");
        }

        return builder;
    }

    private static string FinishHtmlReport(StringBuilder builder)
    {
        builder.AppendLine("</body></html>");
        return builder.ToString();
    }

    private static void AppendHtmlTable(StringBuilder builder, IReadOnlyList<string> headers, IEnumerable<string[]> rows)
    {
        builder.AppendLine("<table border=\"1\" cellspacing=\"0\" cellpadding=\"6\">");
        builder.AppendLine("<thead><tr>");
        foreach (var header in headers)
        {
            builder.AppendLine($"<th>{HtmlEncode(header)}</th>");
        }

        builder.AppendLine("</tr></thead><tbody>");
        var materializedRows = rows.ToList();
        if (materializedRows.Count == 0)
        {
            builder.AppendLine($"<tr><td colspan=\"{headers.Count}\">No data</td></tr>");
        }
        else
        {
            foreach (var row in materializedRows)
            {
                builder.AppendLine("<tr>");
                foreach (var cell in row)
                {
                    builder.AppendLine($"<td>{HtmlEncode(cell)}</td>");
                }

                builder.AppendLine("</tr>");
            }
        }

        builder.AppendLine("</tbody></table>");
    }

    private static string FormatTimelinePeriodLabel(
        NetworkModel network,
        TemporalNetworkSimulationEngine.TemporalSimulationStepResult result)
    {
        if (network.TimelineLoopLength.HasValue && network.TimelineLoopLength.Value > 0)
        {
            return $"Period {result.Period} (cycle period {result.EffectivePeriod} of {network.TimelineLoopLength.Value})";
        }

        return $"Period {result.Period}";
    }

    private static string HtmlEncode(string? value) =>
        WebUtility.HtmlEncode(value ?? string.Empty).Replace(Environment.NewLine, "<br/>");

    private static string FormatOnOff(bool value) => value ? "On" : "Off";

    private static void AppendCsvBranding(StringBuilder builder)
    {
        builder.AppendLine(CsvBrandHeader);
        builder.AppendLine();
    }

    private static void AppendCsvTitleBlock(StringBuilder builder, string title, NetworkModel network)
    {
        builder.AppendLine(BuildCsvRow([title]));
        builder.AppendLine(BuildCsvRow(["Generated", DateTimeOffset.Now.ToString("yyyy-MM-dd HH:mm:ss zzz")]));
        builder.AppendLine(BuildCsvRow(["Network", network.Name]));
        builder.AppendLine(BuildCsvRow(["Sell local meeting-demand limit", FormatOnOff(network.LimitMeetingNodeDemandBySellLocalPermission)]));
        if (!string.IsNullOrWhiteSpace(network.Description))
        {
            builder.AppendLine(BuildCsvRow(["Description", network.Description.Trim()]));
        }

        builder.AppendLine();
    }

    private static void AppendCsvTable(StringBuilder builder, string sectionTitle, IReadOnlyList<string> headers, IEnumerable<string[]> rows)
    {
        builder.AppendLine(BuildCsvRow([sectionTitle]));
        builder.AppendLine(BuildCsvRow(headers));
        var materializedRows = rows.ToList();
        if (materializedRows.Count == 0)
        {
            builder.AppendLine(BuildCsvRow(["No data"]));
        }
        else
        {
            foreach (var row in materializedRows)
            {
                builder.AppendLine(BuildCsvRow(row));
            }
        }

        builder.AppendLine();
    }

    private static string BuildCsvRow(IEnumerable<string?> values) => string.Join(",", values.Select(EscapeCsvCell));

    private static string EscapeCsvCell(string? value)
    {
        var safe = value ?? string.Empty;
        if (safe.Contains('"'))
        {
            safe = safe.Replace("\"", "\"\"");
        }

        return safe.IndexOfAny([',', '"', '\r', '\n']) >= 0 ? $"\"{safe}\"" : safe;
    }
}
